version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: railsathi_db
      POSTGRES_USER: railsathi_user
      POSTGRES_PASSWORD: railsathi_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
